In [3]:
import sys
import numpy as np
import pandas as pd
sys.path.insert(0,'..')
from survey import *

In [5]:
survey = pd.read_csv('/data/togo_anon/surveys/survey2018/survey2018_compiled.csv')
survey.head()

,hhid,GPS__Latitude,GPS__Longitude,walls,roof,floor,water_dry_season,water_wet_season,electricity_access,electricity_use,...,satellite_dish,car,tv_antenna,motorcycle,air_conditioner,tablet,assetindex,cons,cons_basket,weight
0,101,6.159508,1.227120,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0,0,1,0,0,0,1.279984,1299681.0,937653.8,598.23501
1,103,6.159397,1.226654,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,0,1,0,0,0,2.136751,3833842.0,2974120.0,598.23501
2,104,6.159539,1.226442,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0,0,1,0,0,0,1.655253,1338038.0,754271.6,598.23501
3,105,6.159334,1.226387,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0,0,1,0,0,0,0.533043,811542.0,522532.5,598.23501
4,106,6.157822,1.228755,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,0,1,1,0,0,2.252312,2580813.0,2002077.0,598.23501

In [2]:
outcomes_generator = SurveyOutcomeGenerator('../configs/config_emily.yml', clean_folders=True)